project:
  type: book
  output-dir: _book

book:
  title: "Economía Política Formal - 2026"
  chapters:
    - index.qmd
    - chapters/01-interaccion-instituciones-agenda.qmd

lang: es
bibliography: references.bib
number-sections: true

format:
  html:
    toc: true
    code-fold: true
    code-summary: "Mostrar código"
    html-math-method: mathjax

execute:
  freeze: false
